spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:3306/pokemon?createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8091
