version: "3"

x-db-host: &DATABASE_HOST db
x-db-user: &DATABASE_USER root
x-db-password: &DATABASE_PASSWORD root

services:
  web:
    image: mcr.microsoft.com/devcontainers/java:0-17
    tty: true
    working_dir: /app
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      DATABASE_HOST: *DATABASE_HOST
      DATABASE_USER: *DATABASE_USER
      DATABASE_PASSWORD: *DATABASE_PASSWORD
    volumes:
      - ..:/app:delegated
    ports:
      - 8091:8091
    depends_on:
      - db
    command: sleep infinity
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: *DATABASE_PASSWORD
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: *DATABASE_HOST
      PMA_USER: *DATABASE_USER
      PMA_PASSWORD: *DATABASE_PASSWORD
    depends_on:
      - db
volumes:
  db-data:
